In [1]:
import sys
print(sys.executable)

c:\Users\HP\pythoncode\personalized_entertainment_AI\.venv\Scripts\python.exe

In [2]:
import pandas as pd

In [3]:
movies = pd.read_csv("../data/tmdb_5000_movies.csv")

In [4]:
pd.read_csv("../data/tmdb_5000_movies.csv", nrows=5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [6]:
movies.shape

(4803, 20)

In [7]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='str')

In [8]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   str
 2   homepage              1712 non-null   str
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   str
 5   original_language     4803 non-null   str
 6   original_title        4803 non-null   str
 7   overview              4800 non-null   str
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   str
 10  production_countries  4803 non-null   str
 11  release_date          4802 non-null   str
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   str
 15  status                4803 non-null   str
 16  tagline               3959 non-null   str
 17  title                 4803 non-null   str
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), str(13)
memory usage: 750.6 KB

In [9]:
movies.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [10]:
movies.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [11]:
movies.duplicated().sum()

np.int64(0)

In [12]:
(movies['budget'] == 0).sum()

np.int64(1037)

In [4]:
import pandas as pd

In [5]:
movies = pd.read_csv("../data/tmdb_5000_movies.csv")

In [ ]:
(movies['revenue'] == 0).sum()

np.int64(1427)

In [7]:
(movies['runtime'] == 0).sum()

np.int64(35)

In [8]:
movies['genres'].head()

0    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1    [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
Name: genres, dtype: str

In [9]:
movies['keywords'].head()

0    [{"id": 1463, "name": "culture clash"}, {"id":...
1    [{"id": 270, "name": "ocean"}, {"id": 726, "na...
2    [{"id": 470, "name": "spy"}, {"id": 818, "name...
3    [{"id": 849, "name": "dc comics"}, {"id": 853,...
4    [{"id": 818, "name": "based on novel"}, {"id":...
Name: keywords, dtype: str

In [10]:
movies['overview'].head()

0    In the 22nd century, a paraplegic Marine is di...
1    Captain Barbossa, long believed to be dead, ha...
2    A cryptic message from Bond’s past sends him o...
3    Following the death of District Attorney Harve...
4    John Carter is a war-weary, former military ca...
Name: overview, dtype: str

In [11]:
movies['title'].head()

0                                      Avatar
1    Pirates of the Caribbean: At World's End
2                                     Spectre
3                       The Dark Knight Rises
4                                 John Carter
Name: title, dtype: str

In [12]:
import ast

In [13]:
ast.literal_eval(movies['genres'].iloc[0])

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [14]:
genres = ast.literal_eval(movies['genres'].iloc[0])

for genre in genres:
    print(genre['name'])

Action
Adventure
Fantasy
Science Fiction

In [15]:
def convert(obj):
    L = []
    
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    
    return L

In [16]:
convert(movies['genres'].iloc[0])

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [17]:
movies['genres'] = movies['genres'].apply(convert)

In [18]:
movies[['title', 'genres']].head()

,title,genres
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]"
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]"
2,Spectre,"[Action, Adventure, Crime]"
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]"
4,John Carter,"[Action, Adventure, Science Fiction]"

In [19]:
movies[['title', 'keywords']].head()

,title,keywords
0,Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."
2,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name..."
3,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,..."
4,John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":..."

In [20]:
movies['keywords'] = movies['keywords'].apply(convert)

In [21]:
movies[['title', 'keywords']].head()

,title,keywords
0,Avatar,"[culture clash, future, space war, space colon..."
1,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ..."
2,Spectre,"[spy, based on novel, secret agent, sequel, mi..."
3,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i..."
4,John Carter,"[based on novel, mars, medallion, space travel..."

In [23]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='str')

In [24]:
credits.head()

AttributeError: '_Printer' object has no attribute 'head'

In [25]:
print(type(movies))

<class 'pandas.DataFrame'>

In [26]:
%whos

Variable   Type         Data/Info
---------------------------------
ast        module       <module 'ast' from 'C:\\U<...>\Python313\\Lib\\ast.py'>
convert    function     <function convert at 0x000001CDEA4D0360>
genre      dict         n=2
genres     list         n=4
movies     DataFrame    Shape: (4803, 20)
pd         module       <module 'pandas' from 'c:<...>es\\pandas\\__init__.py'>

In [27]:
credits = pd.read_csv('tmdb_5000_credits.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'tmdb_5000_credits.csv'

In [28]:
import os

print(os.getcwd())

c:\Users\HP\pythoncode\personalized_entertainment_AI\notebooks

In [30]:
print(os.listdir())

['01_movies_data_exploration.ipynb']

In [31]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[Action, Adventure, Fantasy, Science Fiction]",http://www.avatarmovie.com/,19995,"[culture clash, future, space war, space colon...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[Adventure, Fantasy, Action]",http://disney.go.com/disneypictures/pirates/,285,"[ocean, drug abuse, exotic island, east india ...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[Action, Adventure, Crime]",http://www.sonypictures.com/movies/spectre/,206647,"[spy, based on novel, secret agent, sequel, mi...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[Action, Crime, Drama, Thriller]",http://www.thedarkknightrises.com/,49026,"[dc comics, crime fighter, terrorist, secret i...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[Action, Adventure, Science Fiction]",http://movies.disney.com/john-carter,49529,"[based on novel, mars, medallion, space travel...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [32]:
credits = pd.read_csv("../data/tmdb_5000_credits.csv")

In [33]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [35]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='str')

In [36]:
movies = movies.merge(credits, left_on='id', right_on='movie_id')

In [37]:
movies.shape

(4803, 24)

In [38]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_x', 'vote_average',
       'vote_count', 'movie_id', 'title_y', 'cast', 'crew'],
      dtype='str')

In [39]:
movies.rename(columns={'title_x': 'title'}, inplace=True)

In [40]:
movies.drop(columns=['title_y', 'movie_id'], inplace=True)

In [41]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'cast', 'crew'],
      dtype='str')

In [42]:
movies['cast'].iloc[0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [43]:
def convert3(obj):
    L = []
    
    for i in ast.literal_eval(obj):
        L.append(i['name'])
        
    return L[:3]

In [44]:
convert3(movies['cast'].iloc[0])

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']

In [45]:
movies['cast'] = movies['cast'].apply(convert3)

In [46]:
movies[['title', 'cast']].head()

,title,cast
0,Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]"
1,Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]"
2,Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]"
3,The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]"
4,John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]"

In [47]:
movies['crew'].iloc[0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [48]:
def fetch_director(obj):
    L = []
    
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
    
    return L

In [49]:
fetch_director(movies['crew'].iloc[0])

['James Cameron']

In [50]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [51]:
movies[['title', 'crew']].head()

                                      title                 crew
0                                    Avatar      [James Cameron]
1  Pirates of the Caribbean: At World's End     [Gore Verbinski]
2                                   Spectre         [Sam Mendes]
3                     The Dark Knight Rises  [Christopher Nolan]
4                               John Carter     [Andrew Stanton]

In [52]:
movies.rename(columns={'crew': 'director'}, inplace=True)

In [54]:
movies[['title', 'director']].head()

                                      title             director
0                                    Avatar      [James Cameron]
1  Pirates of the Caribbean: At World's End     [Gore Verbinski]
2                                   Spectre         [Sam Mendes]
3                     The Dark Knight Rises  [Christopher Nolan]
4                               John Carter     [Andrew Stanton]

In [56]:
movies = movies[['id', 'title', 'overview', 'genres', 'keywords', 'cast', 'director']]

In [57]:
movies.head()

,id,title,overview,genres,keywords,cast,director
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [58]:
movies.isnull().sum()

id          0
title       0
overview    3
genres      0
keywords    0
cast        0
director    0
dtype: int64

In [59]:
movies['overview'] = movies['overview'].fillna('')

In [60]:
movies.head()

,id,title,overview,genres,keywords,cast,director
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [61]:
movies.isnull().sum()

id          0
title       0
overview    0
genres      0
keywords    0
cast        0
director    0
dtype: int64

In [62]:
movies['overview'].iloc[0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [63]:
' '.join(['Action', 'Adventure', 'Fantasy'])

'Action Adventure Fantasy'

In [65]:
movies['genres'] = movies['genres'].apply(lambda x: ' '.join(x))
movies['keywords'] = movies['keywords'].apply(lambda x: ' '.join(x))
movies['cast'] = movies['cast'].apply(lambda x: ' '.join(x))
movies['crew'] = movies['director'].apply(lambda x: ' '.join(x))

In [66]:
movies['tags'] = (
    movies['overview'] + ' ' +
    movies['genres'] + ' ' +
    movies['keywords'] + ' ' +
    movies['cast'] + ' ' +
    movies['crew']
)

In [67]:
movies[['title', 'tags']].head()

,title,tags
0,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,Spectre,A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,Following the death of District Attorney Harve...
4,John Carter,"John Carter is a war-weary, former military ca..."

In [68]:
movies['tags'] = movies['tags'].apply(lambda x: x.lower())

In [69]:
movies['tags'].iloc[0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. a c t i o n   a d v e n t u r e   f a n t a s y   s c i e n c e   f i c t i o n c u l t u r e   c l a s h   f u t u r e   s p a c e   w a r   s p a c e   c o l o n y   s o c i e t y   s p a c e   t r a v e l   f u t u r i s t i c   r o m a n c e   s p a c e   a l i e n   t r i b e   a l i e n   p l a n e t   c g i   m a r i n e   s o l d i e r   b a t t l e   l o v e   a f f a i r   a n t i   w a r   p o w e r   r e l a t i o n s   m i n d   a n d   s o u l   3 d s a m   w o r t h i n g t o n   z o e   s a l d a n a   s i g o u r n e y   w e a v e r james cameron'

In [70]:
from sklearn.feature_extraction.text import CountVectorizer

In [71]:
cv = CountVectorizer(max_features=5000, stop_words='english')

In [72]:
vectors = cv.fit_transform(movies['tags']).toarray()

In [73]:
vectors.shape

(4803, 5000)

In [74]:
from sklearn.metrics.pairwise import cosine_similarity

In [75]:
similarity = cosine_similarity(vectors)

In [76]:
similarity.shape

(4803, 4803)

In [77]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

similarity.shape

(4803, 4803)

In [78]:
def recommend(movie):
    movie_index = movies[movies['title'] == movie].index[0]
    
    distances = similarity[movie_index]
    
    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]
    
    for i in movie_list:
        print(movies.iloc[i[0]].title)

In [79]:
recommend('Avatar')

Apollo 18
Beowulf
Two Lovers
Diamonds Are Forever
Tears of the Sun

In [80]:
def recommend(movie):
    movie_index = movies[movies['title'] == movie].index[0]
    
    distances = similarity[movie_index]
    
    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]
    
    for i in movie_list:
        print(movies.iloc[i[0]].title, "→", i[1])

In [81]:
recommend('Avatar')

Apollo 18 → 0.24494897427831777
Beowulf → 0.21081851067789195
Two Lovers → 0.18257418583505533
Diamonds Are Forever → 0.1690308509457033
Tears of the Sun → 0.15936381457791915

In [82]:
movies[movies['title'] == 'Avatar']['tags'].iloc[0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. a c t i o n   a d v e n t u r e   f a n t a s y   s c i e n c e   f i c t i o n c u l t u r e   c l a s h   f u t u r e   s p a c e   w a r   s p a c e   c o l o n y   s o c i e t y   s p a c e   t r a v e l   f u t u r i s t i c   r o m a n c e   s p a c e   a l i e n   t r i b e   a l i e n   p l a n e t   c g i   m a r i n e   s o l d i e r   b a t t l e   l o v e   a f f a i r   a n t i   w a r   p o w e r   r e l a t i o n s   m i n d   a n d   s o u l   3 d s a m   w o r t h i n g t o n   z o e   s a l d a n a   s i g o u r n e y   w e a v e r james cameron'

In [83]:
movies = pd.read_csv("../data/tmdb_5000_movies.csv")
credits = pd.read_csv("../data/tmdb_5000_credits.csv")

In [84]:
movies = movies.merge(credits, left_on='id', right_on='movie_id')

In [85]:
movies.rename(columns={'title_x': 'title'}, inplace=True)

movies.drop(columns=['title_y', 'movie_id'], inplace=True)

In [86]:
movies = movies[['id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [87]:
movies['overview'] = movies['overview'].fillna('')

In [88]:
def convert(obj):
    L = []
    
    for i in ast.literal_eval(obj):
        L.append(i['name'])
        
    return L

In [89]:
movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)

In [90]:
def convert3(obj):
    L = []
    
    for i in ast.literal_eval(obj):
        L.append(i['name'])
        
    return L[:3]

In [91]:
movies['cast'] = movies['cast'].apply(convert3)

In [92]:
def fetch_director(obj):
    L = []
    
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            
    return L

In [93]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [94]:
movies[['title', 'genres', 'keywords', 'cast', 'crew']].head(1)

,title,genres,keywords,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

In [95]:
movies.rename(columns={'crew': 'director'}, inplace=True)

In [97]:
movies[['title', 'genres', 'keywords', 'cast', 'director']].head(1)

,title,genres,keywords,cast,director
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

In [98]:
movies.columns

Index(['id', 'title', 'overview', 'genres', 'keywords', 'cast', 'director'], dtype='str')

In [99]:
movies[['title', 'director']].head()

                                      title             director
0                                    Avatar      [James Cameron]
1  Pirates of the Caribbean: At World's End     [Gore Verbinski]
2                                   Spectre         [Sam Mendes]
3                     The Dark Knight Rises  [Christopher Nolan]
4                               John Carter     [Andrew Stanton]

In [100]:
movies[['title', 'genres', 'keywords', 'cast', 'director']].head(1)

,title,genres,keywords,cast,director
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

In [101]:
movies['genres'] = movies['genres'].apply(lambda x: ' '.join(x))
movies['keywords'] = movies['keywords'].apply(lambda x: ' '.join(x))
movies['cast'] = movies['cast'].apply(lambda x: ' '.join(x))
movies['director'] = movies['director'].apply(lambda x: ' '.join(x))

In [102]:
movies[['title', 'genres', 'keywords', 'cast', 'director']].head(1)

,title,genres,keywords,cast,director
0,Avatar,Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...,Sam Worthington Zoe Saldana Sigourney Weaver,James Cameron

In [103]:
movies['tags'] = (
    movies['overview'] + ' ' +
    movies['genres'] + ' ' +
    movies['keywords'] + ' ' +
    movies['cast'] + ' ' +
    movies['director']
)

In [104]:
movies['tags'].iloc[0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy Science Fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d Sam Worthington Zoe Saldana Sigourney Weaver James Cameron'

In [105]:
movies['tags'] = movies['tags'].apply(lambda x: x.lower())

In [106]:
movies['tags'].iloc[0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy science fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d sam worthington zoe saldana sigourney weaver james cameron'

In [107]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')

vectors = cv.fit_transform(movies['tags']).toarray()

In [108]:
vectors.shape

(4803, 5000)

In [109]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

In [110]:
similarity.shape

(4803, 4803)

In [111]:
recommend('Avatar')

Aliens → 0.4839354795704658
Moonraker → 0.4335521648830699
Alien → 0.4248170000930695
Alien³ → 0.3962969619506085
Silent Running → 0.39207842352784267

In [112]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [113]:
tfidf = TfidfVectorizer(max_features=5000, stop_words='english')

In [114]:
vectors = tfidf.fit_transform(movies['tags']).toarray()

In [115]:
vectors.shape

(4803, 5000)

In [116]:
similarity = cosine_similarity(vectors)

In [117]:
similarity.shape

(4803, 4803)

In [118]:
recommend('Avatar')

Aliens → 0.4295289742539938
Alien → 0.35839642749626904
Moonraker → 0.34929129022286776
Alien³ → 0.34730619334095447
Silent Running → 0.3151101161942778

In [119]:
def recommend(movie):
    movie_index = movies[movies['title'] == movie].index[0]
    
    distances = similarity[movie_index]
    
    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]
    
    recommendations = []
    
    for i in movie_list:
        recommendations.append(movies.iloc[i[0]].title)
    
    return recommendations

In [120]:
recommend('Avatar')

['Aliens', 'Alien', 'Moonraker', 'Alien³', 'Silent Running']

In [121]:
def recommend(movie):
    movie_index = movies[movies['title'].str.lower() == movie.lower()].index[0]
    
    distances = similarity[movie_index]
    
    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]
    
    recommendations = []
    
    for i in movie_list:
        recommendations.append(movies.iloc[i[0]].title)
    
    return recommendations

In [122]:
recommend('avatar')

['Aliens', 'Alien', 'Moonraker', 'Alien³', 'Silent Running']

In [123]:
def recommend(movie):
    matches = movies[movies['title'].str.lower() == movie.lower()]
    
    if matches.empty:
        return "Movie not found in dataset."
    
    movie_index = matches.index[0]
    
    distances = similarity[movie_index]
    
    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]
    
    recommendations = []
    
    for i in movie_list:
        recommendations.append(movies.iloc[i[0]].title)
    
    return recommendations

In [124]:
recommend('Batman Begins')

['The Dark Knight',
 'The Dark Knight Rises',
 'Batman',
 'Batman Returns',
 'Batman v Superman: Dawn of Justice']

In [125]:
recommend('avengers 2026')

'Movie not found in dataset.'

In [126]:
recommend('Titanic')

['Romance & Cigarettes',
 'Captain Phillips',
 'Ghost Ship',
 'Poseidon',
 'Triangle']

In [127]:
recommend('The Dark Knight Rises')

['The Dark Knight',
 'Batman Returns',
 'Batman Begins',
 'Batman',
 'Batman Forever']

In [128]:
recommend('The Hangover')

['The Hangover Part II',
 'Last Vegas',
 'Very Bad Things',
 'What Happens in Vegas',
 'Cool Runnings']

In [129]:
similarity[0]

array([1.        , 0.02150704, 0.02241544, ..., 0.00945769, 0.03335591,
       0.        ], shape=(4803,))

In [130]:
movies[['title', 'genres']].head()

,title,genres
0,Avatar,Action Adventure Fantasy Science Fiction
1,Pirates of the Caribbean: At World's End,Adventure Fantasy Action
2,Spectre,Action Adventure Crime
3,The Dark Knight Rises,Action Crime Drama Thriller
4,John Carter,Action Adventure Science Fiction

In [131]:
original_movies = pd.read_csv("../data/tmdb_5000_movies.csv")

In [132]:
original_movies['genre_list'] = original_movies['genres'].apply(convert)

In [133]:
movies = movies.merge(
    original_movies[['id', 'genre_list']],
    on='id',
    how='left'
)

In [134]:
movies[['title', 'genres', 'genre_list']].head()

,title,genres,genre_list
0,Avatar,Action Adventure Fantasy Science Fiction,"[Action, Adventure, Fantasy, Science Fiction]"
1,Pirates of the Caribbean: At World's End,Adventure Fantasy Action,"[Adventure, Fantasy, Action]"
2,Spectre,Action Adventure Crime,"[Action, Adventure, Crime]"
3,The Dark Knight Rises,Action Crime Drama Thriller,"[Action, Crime, Drama, Thriller]"
4,John Carter,Action Adventure Science Fiction,"[Action, Adventure, Science Fiction]"

In [135]:
movies[['title', 'genre_list']].head()

,title,genre_list
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]"
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]"
2,Spectre,"[Action, Adventure, Crime]"
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]"
4,John Carter,"[Action, Adventure, Science Fiction]"

In [136]:
def get_genres(movie_index):
    return set(movies.iloc[movie_index]['genre_list'])

In [137]:
avatar_index = movies[movies['title'] == 'Avatar'].index[0]

In [138]:
get_genres(avatar_index)

{'Action', 'Adventure', 'Fantasy', 'Science Fiction'}

In [139]:
aliens_index = movies[movies['title'] == 'Aliens'].index[0]

In [140]:
get_genres(aliens_index)

{'Action', 'Horror', 'Science Fiction', 'Thriller'}

In [141]:
get_genres(avatar_index) & get_genres(aliens_index)

{'Action', 'Science Fiction'}

In [142]:
def genre_overlap_score(movie):
    matches = movies[movies['title'].str.lower() == movie.lower()]
    
    if matches.empty:
        return None
    
    movie_index = matches.index[0]
    movie_genres = set(movies.iloc[movie_index]['genre_list'])
    
    distances = similarity[movie_index]
    
    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]
    
    relevant = 0
    
    for i in movie_list:
        recommended_genres = set(movies.iloc[i[0]]['genre_list'])
        
        if movie_genres & recommended_genres:
            relevant += 1
    
    return relevant / 5

In [143]:
genre_overlap_score('Avatar')

1.0

In [144]:
genre_overlap_score('The Hangover')

1.0

In [145]:
genre_overlap_score('The Dark Knight Rises')

1.0

In [ ]:
def genre_coverage_score(movie):
    matches = movies[movies['title'].str.lower() == movie.lower()]
    
    if matches.empty:
        return None
    
    movie_index = matches.index[0]
    movie_genres = set(movies.iloc[movie_index]['genre_list'])
    
    distances = similarity[movie_index]
    
    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]
    
    total_overlap = 0
    
    for i in movie_list:
        recommended_genres = set(movies.iloc[i[0]]['genre_list'])
        
        overlap = len(movie_genres & recommended_genres) / len(movie_genres)
        
        total_overlap += overlap
    
    return total_overlap / 5
# 1.0 → recommendations cover all original genres
# 0.5 → on average, half the original genres are represented
# 0.0 → no genre overlap

In [147]:
genre_coverage_score('Avatar')

0.55

In [148]:
genre_coverage_score('The Hangover')

1.0

In [149]:
genre_coverage_score('The Dark Knight Rises')

0.55

In [150]:
import random

random.seed(42)

test_indices = random.sample(range(len(movies)), 100)

In [151]:
scores = []

for index in test_indices:
    title = movies.iloc[index]['title']
    score = genre_coverage_score(title)
    
    if score is not None:
        scores.append(score)

ZeroDivisionError: division by zero

In [152]:
def genre_coverage_score(movie):
    matches = movies[movies['title'].str.lower() == movie.lower()]
    
    if matches.empty:
        return None
    
    movie_index = matches.index[0]
    movie_genres = set(movies.iloc[movie_index]['genre_list'])
    
    if len(movie_genres) == 0:
        return None
    
    distances = similarity[movie_index]
    
    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]
    
    total_overlap = 0
    
    for i in movie_list:
        recommended_genres = set(movies.iloc[i[0]]['genre_list'])
        
        overlap = len(movie_genres & recommended_genres) / len(movie_genres)
        
        total_overlap += overlap
    
    return total_overlap / 5

In [153]:
scores = []

for index in test_indices:
    title = movies.iloc[index]['title']
    score = genre_coverage_score(title)
    
    if score is not None:
        scores.append(score)

In [154]:
average_score = sum(scores) / len(scores)

average_score

0.502895622895623

In [155]:
len(scores)

99

In [2]:
import sentence_transformers

In [1]:
from sentence_transformers import SentenceTransformer

In [2]:
model = SentenceTransformer('all-MiniLM-L6-v2')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

c:\Users\HP\pythoncode\personalized_entertainment_AI\.venv\Lib\site-packages\huggingface_hub\file_download.py:141: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\HP\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [3]:
model

SentenceTransformer(
  (0): Transformer({'transformer_task': 'feature-extraction', 'modality_config': {'text': {'method': 'forward', 'method_output_name': 'last_hidden_state'}}, 'module_output_name': 'token_embeddings', 'architecture': 'BertModel'})
  (1): Pooling({'embedding_dimension': 384, 'pooling_mode': 'mean', 'include_prompt': True})
  (2): Normalize({'module_input_name': 'sentence_embedding', 'module_output_name': 'sentence_embedding'})
)

In [7]:
import pandas as pd
import ast

In [8]:
movies = pd.read_csv("../data/tmdb_5000_movies.csv")

In [9]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='str')

In [10]:
def convert(text):
    result = []
    
    for item in ast.literal_eval(text):
        result.append(item['name'])
        
    return result

In [11]:
movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)

In [12]:
credits = pd.read_csv("../data/tmdb_5000_credits.csv")

In [13]:
movies = movies.merge(
    credits[['movie_id', 'title', 'cast', 'crew']],
    left_on='id',
    right_on='movie_id'
)

In [14]:
def get_director(text):
    for person in ast.literal_eval(text):
        if person['job'] == 'Director':
            return person['name']
    return ''

In [15]:
movies['director'] = movies['crew'].apply(get_director)

In [16]:
movies['cast'] = movies['cast'].apply(
    lambda x: [item['name'] for item in ast.literal_eval(x)[:3]]
)

In [17]:
movies['tags'] = (
    movies['overview'].fillna('') + ' ' +
    movies['genres'].apply(lambda x: ' '.join(x)) + ' ' +
    movies['keywords'].apply(lambda x: ' '.join(x)) + ' ' +
    movies['cast'].apply(lambda x: ' '.join(x)) + ' ' +
    movies['director'].fillna('')
)

In [18]:
movies['tags'] = movies['tags'].str.lower()

In [19]:
movies[movies['title_x'] == 'Avatar']['tags'].iloc[0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy science fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d sam worthington zoe saldana sigourney weaver james cameron'

In [20]:
avatar_index = movies[movies['title_x'] == 'Avatar'].index[0]

avatar_embedding = model.encode(
    movies.loc[avatar_index, 'tags']
)

In [21]:
avatar_embedding.shape

(384,)

In [22]:
avatar_embedding[:10]

array([-0.02394136, -0.04226302,  0.00827299, -0.04955373, -0.07312015,
       -0.00112701, -0.00066598, -0.09791557,  0.03918725,  0.00894446],
      dtype=float32)

In [23]:
aliens_index = movies[movies['title_x'] == 'Aliens'].index[0]

aliens_embedding = model.encode(
    movies.loc[aliens_index, 'tags']
)

In [24]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(
    [avatar_embedding],
    [aliens_embedding]
)

array([[0.5140847]], dtype=float32)

In [25]:
movie_embeddings = model.encode(
    movies['tags'].tolist(),
    show_progress_bar=True
)

Batches:   0%|          | 0/151 [00:00<?, ?it/s]

In [26]:
movie_embeddings.shape

(4803, 384)

In [27]:
movie_embeddings = model.encode(
    movies['tags'].tolist(),
    show_progress_bar=True
)

Batches:   0%|          | 0/151 [00:00<?, ?it/s]

In [28]:
movie_embeddings.shape

(4803, 384)

In [29]:
import numpy as np

np.save("../data/movie_embeddings.npy", movie_embeddings)

In [30]:
loaded_embeddings = np.load("../data/movie_embeddings.npy")

loaded_embeddings.shape

(4803, 384)

In [31]:
from sklearn.metrics.pairwise import cosine_similarity

embedding_similarity = cosine_similarity(movie_embeddings)

In [32]:
embedding_similarity.shape

(4803, 4803)

In [33]:
def recommend_semantic(movie):
    matches = movies[movies['title_x'].str.lower() == movie.lower()]
    
    if matches.empty:
        return []
    
    movie_index = matches.index[0]
    
    distances = embedding_similarity[movie_index]
    
    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]
    
    return [movies.iloc[i[0]]['title_x'] for i in movie_list]

In [34]:
recommend_semantic('Avatar')

['Serenity',
 'Jupiter Ascending',
 'Star Trek Into Darkness',
 'Barbarella',
 'Aliens']

In [35]:
def genre_coverage_score_semantic(movie):
    matches = movies[movies['title_x'].str.lower() == movie.lower()]
    
    if matches.empty:
        return None
    
    movie_index = matches.index[0]
    movie_genres = set(movies.iloc[movie_index]['genre_list'])
    
    if len(movie_genres) == 0:
        return None
    
    distances = embedding_similarity[movie_index]
    
    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]
    
    total_overlap = 0
    
    for i in movie_list:
        recommended_genres = set(movies.iloc[i[0]]['genre_list'])
        
        overlap = len(movie_genres & recommended_genres) / len(movie_genres)
        
        total_overlap += overlap
    
    return total_overlap / 5

In [37]:
import random

random.seed(42)

test_indices = random.sample(range(len(movies)), 100)

In [39]:
movies['genre_list'] = movies['genres'].apply(
    lambda x: x if isinstance(x, list) else ast.literal_eval(x)
)

In [40]:
type(movies['genres'].iloc[0])

list

In [41]:
movies['genre_list'] = movies['genres'].copy()

In [42]:
movies[['title_x', 'genre_list']].head()

,title_x,genre_list
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]"
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]"
2,Spectre,"[Action, Adventure, Crime]"
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]"
4,John Carter,"[Action, Adventure, Science Fiction]"

In [43]:
semantic_scores = []

for index in test_indices:
    title = movies.iloc[index]['title_x']
    score = genre_coverage_score_semantic(title)
    
    if score is not None:
        semantic_scores.append(score)

In [44]:
semantic_average_score = sum(semantic_scores) / len(semantic_scores)

semantic_average_score

0.5317508417508418

In [45]:
len(semantic_scores)

99

In [46]:
def feature_coverage_score_semantic(movie):
    matches = movies[movies['title_x'].str.lower() == movie.lower()]
    
    if matches.empty:
        return None
    
    movie_index = matches.index[0]
    
    # Features of the original movie
    movie_genres = set(movies.iloc[movie_index]['genre_list'])
    movie_keywords = set(movies.iloc[movie_index]['keywords'])
    movie_cast = set(movies.iloc[movie_index]['cast'])
    movie_director = movies.iloc[movie_index]['director']
    
    # Find top 5 recommendations
    distances = embedding_similarity[movie_index]
    
    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]
    
    total_score = 0
    
    for i in movie_list:
        recommended = movies.iloc[i[0]]
        
        recommended_genres = set(recommended['genre_list'])
        recommended_keywords = set(recommended['keywords'])
        recommended_cast = set(recommended['cast'])
        recommended_director = recommended['director']
        
        # Genre overlap
        genre_score = (
            len(movie_genres & recommended_genres) / len(movie_genres)
            if movie_genres else 0
        )
        
        # Keyword overlap
        keyword_score = (
            len(movie_keywords & recommended_keywords) / len(movie_keywords)
            if movie_keywords else 0
        )
        
        # Cast overlap
        cast_score = (
            len(movie_cast & recommended_cast) / len(movie_cast)
            if movie_cast else 0
        )
        
        # Director match
        director_score = (
            1 if movie_director == recommended_director
            and movie_director != ''
            else 0
        )
        
        # Combine the four signals
        recommendation_score = (
            genre_score +
            keyword_score +
            cast_score +
            director_score
        ) / 4
        
        total_score += recommendation_score
    
    return total_score / 5

In [47]:
semantic_feature_scores = []

for index in test_indices:
    title = movies.iloc[index]['title_x']
    
    score = feature_coverage_score_semantic(title)
    
    if score is not None:
        semantic_feature_scores.append(score)

In [48]:
semantic_feature_average = (
    sum(semantic_feature_scores)
    / len(semantic_feature_scores)
)

semantic_feature_average

0.1683202324051937

In [49]:
len(semantic_feature_scores)

100

In [50]:
def feature_coverage_score_tfidf(movie):
    matches = movies[movies['title_x'].str.lower() == movie.lower()]
    
    if matches.empty:
        return None
    
    movie_index = matches.index[0]
    
    movie_genres = set(movies.iloc[movie_index]['genre_list'])
    movie_keywords = set(movies.iloc[movie_index]['keywords'])
    movie_cast = set(movies.iloc[movie_index]['cast'])
    movie_director = movies.iloc[movie_index]['director']
    
    distances = similarity[movie_index]
    
    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]
    
    total_score = 0
    
    for i in movie_list:
        recommended = movies.iloc[i[0]]
        
        recommended_genres = set(recommended['genre_list'])
        recommended_keywords = set(recommended['keywords'])
        recommended_cast = set(recommended['cast'])
        recommended_director = recommended['director']
        
        genre_score = (
            len(movie_genres & recommended_genres) / len(movie_genres)
            if movie_genres else 0
        )
        
        keyword_score = (
            len(movie_keywords & recommended_keywords) / len(movie_keywords)
            if movie_keywords else 0
        )
        
        cast_score = (
            len(movie_cast & recommended_cast) / len(movie_cast)
            if movie_cast else 0
        )
        
        director_score = (
            1 if movie_director == recommended_director
            and movie_director != ''
            else 0
        )
        
        recommendation_score = (
            genre_score +
            keyword_score +
            cast_score +
            director_score
        ) / 4
        
        total_score += recommendation_score
    
    return total_score / 5

In [51]:
tfidf_feature_scores = []

for index in test_indices:
    title = movies.iloc[index]['title_x']
    
    score = feature_coverage_score_tfidf(title)
    
    if score is not None:
        tfidf_feature_scores.append(score)

NameError: name 'similarity' is not defined

In [52]:
import os

os.path.exists("../data/similarity.pkl")

False

In [53]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [54]:
tfidf = TfidfVectorizer(max_features=5000, stop_words='english')

In [55]:
tfidf_matrix = tfidf.fit_transform(movies['tags'])

In [56]:
tfidf_matrix.shape

(4803, 5000)

In [57]:
similarity = cosine_similarity(tfidf_matrix)

In [58]:
similarity.shape

(4803, 4803)

In [59]:
tfidf_feature_scores = []

for index in test_indices:
    title = movies.iloc[index]['title_x']
    
    score = feature_coverage_score_tfidf(title)
    
    if score is not None:
        tfidf_feature_scores.append(score)

In [60]:
tfidf_feature_average = (
    sum(tfidf_feature_scores)
    / len(tfidf_feature_scores)
)

tfidf_feature_average

0.19221736793521235

In [61]:
len(tfidf_feature_scores)

100

In [62]:
def compare_recommendations(movie):
    
    print("MOVIE:", movie)
    print("\nTF-IDF:")
    
    tfidf_recommendations = recommend(movie)
    
    for i, title in enumerate(tfidf_recommendations, 1):
        print(i, title)
    
    print("\nSEMANTIC:")
    
    semantic_recommendations = recommend_semantic(movie)
    
    for i, title in enumerate(semantic_recommendations, 1):
        print(i, title)

In [64]:
def recommend_tfidf(movie):
    matches = movies[movies['title_x'].str.lower() == movie.lower()]
    
    if matches.empty:
        return []
    
    movie_index = matches.index[0]
    
    distances = similarity[movie_index]
    
    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]
    
    return [movies.iloc[i[0]]['title_x'] for i in movie_list]

In [65]:
def compare_recommendations(movie):
    
    print("MOVIE:", movie)
    
    print("\nTF-IDF:")
    tfidf_recommendations = recommend_tfidf(movie)
    
    for i, title in enumerate(tfidf_recommendations, 1):
        print(i, title)
    
    print("\nSEMANTIC:")
    semantic_recommendations = recommend_semantic(movie)
    
    for i, title in enumerate(semantic_recommendations, 1):
        print(i, title)

In [66]:
compare_recommendations('Avatar')

MOVIE: Avatar

TF-IDF:
1 Aliens
2 Alien
3 Moonraker
4 Alien³
5 Silent Running

SEMANTIC:
1 Serenity
2 Jupiter Ascending
3 Star Trek Into Darkness
4 Barbarella
5 Aliens

In [67]:
compare_recommendations('The Dark Knight')

MOVIE: The Dark Knight

TF-IDF:
1 The Dark Knight Rises
2 Batman Begins
3 Batman Returns
4 Batman Forever
5 Batman v Superman: Dawn of Justice

SEMANTIC:
1 The Dark Knight Rises
2 Batman Begins
3 Batman
4 Batman & Robin
5 Batman v Superman: Dawn of Justice

In [68]:
compare_recommendations('The Hangover Part II')

MOVIE: The Hangover Part II

TF-IDF:
1 The Hangover
2 Last Vegas
3 Bachelorette
4 What Happens in Vegas
5 That's My Boy

SEMANTIC:
1 Reno 911!: Miami
2 My Best Friend's Girl
3 Half Baked
4 Very Bad Things
5 Bachelorette

In [3]:
import os

print(os.getcwd())

c:\Users\HP\pythoncode\personalized_entertainment_AI\notebooks

In [4]:
os.listdir()

['01_movies_data_exploration.ipynb']

In [5]:
os.listdir("..")

['.git', '.venv', 'data', 'notebooks', 'README.md', 'src']

In [6]:
os.listdir("../data")

['movie_embeddings.npy', 'tmdb_5000_credits.csv', 'tmdb_5000_movies.csv']

In [7]:
import pandas as pd
import ast
import numpy as np

movies_df = pd.read_csv("../data/tmdb_5000_movies.csv")
credits_df = pd.read_csv("../data/tmdb_5000_credits.csv")

In [8]:
movies = movies_df.merge(
    credits_df,
    left_on="id",
    right_on="movie_id"
)

In [9]:
movies.shape

(4803, 24)

In [10]:
movies = movies.rename(columns={"title_x": "title"})

In [11]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'title_y', 'cast', 'crew'],
      dtype='str')

In [12]:
def extract_names(text):
    try:
        return [item["name"].lower() for item in ast.literal_eval(text)]
    except:
        return []

In [13]:
movies["genre_list"] = movies["genres"].apply(extract_names)

In [14]:
movies["keyword_list"] = movies["keywords"].apply(extract_names)

In [15]:
def extract_cast(text):
    try:
        return [
            item["name"].lower()
            for item in ast.literal_eval(text)[:5]
        ]
    except:
        return []

In [16]:
movies["cast_list"] = movies["cast"].apply(extract_cast)

In [17]:
def extract_director(text):
    try:
        crew = ast.literal_eval(text)
        
        for item in crew:
            if item["job"] == "Director":
                return item["name"].lower()
        
        return ""
    except:
        return ""

In [18]:
movies["director"] = movies["crew"].apply(extract_director)

In [19]:
movies["tags"] = (
    movies["overview"].fillna("") + " " +
    movies["genres"].fillna("") + " " +
    movies["keywords"].fillna("") + " " +
    movies["cast"].fillna("") + " " +
    movies["director"].fillna("")
).str.lower()

In [20]:
movies[["title", "tags"]].head()

,title,tags
0,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,Spectre,a cryptic message from bond’s past sends him o...
3,The Dark Knight Rises,following the death of district attorney harve...
4,John Carter,"john carter is a war-weary, former military ca..."

In [21]:
movie_embeddings = np.load("../data/movie_embeddings.npy")

In [22]:
movie_embeddings.shape

(4803, 384)

In [23]:
movies.shape

(4803, 29)

In [24]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'title_y', 'cast', 'crew', 'genre_list',
       'keyword_list', 'cast_list', 'director', 'tags'],
      dtype='str')

In [25]:
movie_embeddings.shape

(4803, 384)

In [26]:
from sklearn.metrics.pairwise import cosine_similarity

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words='english'
)

tfidf_matrix = tfidf.fit_transform(movies['tags'])

similarity = cosine_similarity(tfidf_matrix)

In [28]:
similarity.shape

(4803, 4803)

In [29]:
embedding_similarity = cosine_similarity(movie_embeddings)

In [30]:
embedding_similarity.shape

(4803, 4803)

In [31]:
tfidf_min = similarity.min(axis=1, keepdims=True)
tfidf_max = similarity.max(axis=1, keepdims=True)

tfidf_normalized = (
    similarity - tfidf_min
) / (tfidf_max - tfidf_min)

In [32]:
semantic_min = embedding_similarity.min(axis=1, keepdims=True)
semantic_max = embedding_similarity.max(axis=1, keepdims=True)

semantic_normalized = (
    embedding_similarity - semantic_min
) / (semantic_max - semantic_min)

In [33]:
tfidf_normalized.shape
semantic_normalized.shape

(4803, 4803)

In [34]:
tfidf_normalized.shape

(4803, 4803)

In [35]:

tfidf_normalized.shape, semantic_normalized.shape

((4803, 4803), (4803, 4803))

In [36]:
hybrid_similarity = (
    0.5 * tfidf_normalized
    + 0.5 * semantic_normalized
)

In [37]:
hybrid_similarity.shape

(4803, 4803)

In [38]:
def recommend_hybrid(movie):
    
    matches = movies[
        movies['title'].str.lower() == movie.lower()
    ]
    
    if matches.empty:
        return []
    
    movie_index = matches.index[0]
    
    distances = hybrid_similarity[movie_index]
    
    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]
    
    return [
        movies.iloc[i[0]]['title']
        for i in movie_list
    ]

In [39]:
recommend_hybrid('Avatar')

['Jupiter Ascending',
 'Serenity',
 'Close Encounters of the Third Kind',
 'Barbarella',
 'Battle: Los Angeles']

In [40]:
recommend_hybrid('The Dark Knight')

['The Dark Knight Rises',
 'Batman Begins',
 'Batman v Superman: Dawn of Justice',
 'Batman',
 'Suicide Squad']

In [41]:
recommend_hybrid('The Hangover Part II')

["My Best Friend's Girl",
 'The Hangover',
 'Diner',
 'Superbad',
 'American Pie 2']

In [42]:
import numpy as np

np.random.seed(42)

test_indices = np.random.choice(
    len(movies),
    size=100,
    replace=False
)

len(test_indices)

100

In [43]:
def get_hybrid_similarity(tfidf_weight):
    
    semantic_weight = 1 - tfidf_weight
    
    return (
        tfidf_weight * tfidf_normalized
        + semantic_weight * semantic_normalized
    )

In [44]:
def evaluate_hybrid(tfidf_weight):
    
    hybrid = get_hybrid_similarity(tfidf_weight)
    
    scores = []
    
    for index in test_indices:
        
        movie_genres = set(movies.iloc[index]['genre_list'])
        movie_keywords = set(movies.iloc[index]['keyword_list'])
        movie_cast = set(movies.iloc[index]['cast_list'])
        movie_director = movies.iloc[index]['director']
        
        if len(movie_genres) == 0:
            continue
        
        distances = hybrid[index]
        
        movie_list = sorted(
            list(enumerate(distances)),
            reverse=True,
            key=lambda x: x[1]
        )[1:6]
        
        total_score = 0
        
        for i in movie_list:
            
            recommended = movies.iloc[i[0]]
            
            recommended_genres = set(
                recommended['genre_list']
            )
            
            recommended_keywords = set(
                recommended['keyword_list']
            )
            
            recommended_cast = set(
                recommended['cast_list']
            )
            
            recommended_director = recommended['director']
            
            genre_score = (
                len(movie_genres & recommended_genres)
                / len(movie_genres)
            )
            
            keyword_score = (
                len(movie_keywords & recommended_keywords)
                / len(movie_keywords)
                if movie_keywords else 0
            )
            
            cast_score = (
                len(movie_cast & recommended_cast)
                / len(movie_cast)
                if movie_cast else 0
            )
            
            director_score = (
                1
                if movie_director
                and movie_director == recommended_director
                else 0
            )
            
            feature_score = (
                genre_score
                + keyword_score
                + cast_score
                + director_score
            ) / 4
            
            total_score += feature_score
        
        scores.append(total_score / 5)
    
    return np.mean(scores), len(scores)

In [45]:
weights = [
    0.0,
    0.2,
    0.4,
    0.5,
    0.6,
    0.8,
    1.0
]

results = []

for weight in weights:
    
    score, count = evaluate_hybrid(weight)
    
    results.append({
        'tfidf_weight': weight,
        'semantic_weight': 1 - weight,
        'score': score,
        'movies_evaluated': count
    })

results

[{'tfidf_weight': 0.0,
  'semantic_weight': 1.0,
  'score': np.float64(0.1892347880981304),
  'movies_evaluated': 99},
 {'tfidf_weight': 0.2,
  'semantic_weight': 0.8,
  'score': np.float64(0.19394536230323184),
  'movies_evaluated': 99},
 {'tfidf_weight': 0.4,
  'semantic_weight': 0.6,
  'score': np.float64(0.19400750726332305),
  'movies_evaluated': 99},
 {'tfidf_weight': 0.5,
  'semantic_weight': 0.5,
  'score': np.float64(0.1919798209530546),
  'movies_evaluated': 99},
 {'tfidf_weight': 0.6,
  'semantic_weight': 0.4,
  'score': np.float64(0.18817517442113532),
  'movies_evaluated': 99},
 {'tfidf_weight': 0.8,
  'semantic_weight': 0.19999999999999996,
  'score': np.float64(0.1739090949564408),
  'movies_evaluated': 99},
 {'tfidf_weight': 1.0,
  'semantic_weight': 0.0,
  'score': np.float64(0.13331957894304589),
  'movies_evaluated': 99}]

In [46]:
import pandas as pd

results_df = pd.DataFrame(results)

results_df

   tfidf_weight  semantic_weight     score  movies_evaluated
0           0.0              1.0  0.189235                99
1           0.2              0.8  0.193945                99
2           0.4              0.6  0.194008                99
3           0.5              0.5  0.191980                99
4           0.6              0.4  0.188175                99
5           0.8              0.2  0.173909                99
6           1.0              0.0  0.133320                99

In [47]:
results_df.sort_values(
    'score',
    ascending=False
)

   tfidf_weight  semantic_weight     score  movies_evaluated
2           0.4              0.6  0.194008                99
1           0.2              0.8  0.193945                99
3           0.5              0.5  0.191980                99
0           0.0              1.0  0.189235                99
4           0.6              0.4  0.188175                99
5           0.8              0.2  0.173909                99
6           1.0              0.0  0.133320                99

In [51]:
np.random.seed(123)

test_indices_final = np.random.choice(
    len(movies),
    size=100,
    replace=False
)

len(test_indices_final)

100

In [49]:
len(set(test_indices) & set(test_indices_final))

1

In [52]:
np.random.seed(123)

test_indices_final = np.random.choice(
    list(set(range(len(movies))) - set(test_indices)),
    size=100,
    replace=False
)

In [53]:
len(set(test_indices) & set(test_indices_final))

0

In [54]:
len(test_indices_final)

100

In [56]:
def evaluate_hybrid_on_indices(tfidf_weight, indices):
    
    hybrid = get_hybrid_similarity(tfidf_weight)
    
    scores = []
    
    for index in indices:
        
        movie_genres = set(movies.iloc[index]['genre_list'])
        movie_keywords = set(movies.iloc[index]['keyword_list'])
        movie_cast = set(movies.iloc[index]['cast_list'])
        movie_director = movies.iloc[index]['director']
        
        if len(movie_genres) == 0:
            continue
        
        distances = hybrid[index]
        
        movie_list = sorted(
            list(enumerate(distances)),
            reverse=True,
            key=lambda x: x[1]
        )[1:6]
        
        total_score = 0
        
        for i in movie_list:
            
            recommended = movies.iloc[i[0]]
            
            recommended_genres = set(
                recommended['genre_list']
            )
            
            recommended_keywords = set(
                recommended['keyword_list']
            )
            
            recommended_cast = set(
                recommended['cast_list']
            )
            
            recommended_director = recommended['director']
            
            genre_score = (
                len(movie_genres & recommended_genres)
                / len(movie_genres)
            )
            
            keyword_score = (
                len(movie_keywords & recommended_keywords)
                / len(movie_keywords)
                if movie_keywords else 0
            )
            
            cast_score = (
                len(movie_cast & recommended_cast)
                / len(movie_cast)
                if movie_cast else 0
            )
            
            director_score = (
                1
                if movie_director
                and movie_director == recommended_director
                else 0
            )
            
            feature_score = (
                genre_score
                + keyword_score
                + cast_score
                + director_score
            ) / 4
            
            total_score += feature_score
        
        scores.append(total_score / 5)
    
    return np.mean(scores), len(scores)

In [57]:
final_score, final_count = evaluate_hybrid_on_indices(
    0.4,
    test_indices_final
)

final_score, final_count

(np.float64(0.17371919905512406), 99)

In [58]:
tfidf_test_score, tfidf_test_count = evaluate_hybrid_on_indices(
    1.0,
    test_indices_final
)

semantic_test_score, semantic_test_count = evaluate_hybrid_on_indices(
    0.0,
    test_indices_final
)

hybrid_test_score, hybrid_test_count = evaluate_hybrid_on_indices(
    0.4,
    test_indices_final
)

In [59]:
print("TF-IDF:", tfidf_test_score, tfidf_test_count)
print("Semantic:", semantic_test_score, semantic_test_count)
print("Hybrid:", hybrid_test_score, hybrid_test_count)

TF-IDF: 0.11550925645622614 99
Semantic: 0.16996766527966684 99
Hybrid: 0.17371919905512406 99

In [60]:
import os

os.makedirs("../data/artifacts", exist_ok=True)

In [61]:
import joblib

joblib.dump(
    tfidf,
    "../data/artifacts/tfidf_vectorizer.pkl"
)

['../data/artifacts/tfidf_vectorizer.pkl']

In [62]:
from scipy.sparse import save_npz

save_npz(
    "../data/artifacts/tfidf_matrix.npz",
    tfidf_matrix
)

In [63]:
np.save(
    "../data/artifacts/tfidf_similarity.npy",
    similarity
)

In [64]:
np.save(
    "../data/artifacts/semantic_similarity.npy",
    embedding_similarity
)

In [66]:
np.save(
    "../data/artifacts/tfidf_normalized.npy",
    tfidf_normalized
)

np.save(
    "../data/artifacts/semantic_normalized.npy",
    semantic_normalized
)

In [67]:
hybrid_similarity = (
    0.4 * tfidf_normalized
    + 0.6 * semantic_normalized
)

np.save(
    "../data/artifacts/hybrid_similarity.npy",
    hybrid_similarity
)

In [68]:
movies.to_pickle(
    "../data/artifacts/movies_processed.pkl"
)

In [69]:
os.listdir("../data/artifacts")

['hybrid_similarity.npy',
 'movies_processed.pkl',
 'semantic_normalized.npy',
 'semantic_similarity.npy',
 'tfidf_matrix.npz',
 'tfidf_normalized.npy',
 'tfidf_similarity.npy',
 'tfidf_vectorizer.pkl']

In [70]:
os.listdir("../src")

[]

In [71]:
def genre_similarity(movie_index, candidate_index):
    
    movie_genres = set(
        movies.iloc[movie_index]['genre_list']
    )
    
    candidate_genres = set(
        movies.iloc[candidate_index]['genre_list']
    )
    
    if not movie_genres:
        return 0
    
    return len(
        movie_genres & candidate_genres
    ) / len(movie_genres)

In [72]:
avatar_index = movies[
    movies['title'].str.lower() == 'avatar'
].index[0]

serenity_index = movies[
    movies['title'].str.lower() == 'serenity'
].index[0]

genre_similarity(
    avatar_index,
    serenity_index
)

0.75

In [73]:
def keyword_similarity(movie_index, candidate_index):
    
    movie_keywords = set(
        movies.iloc[movie_index]['keyword_list']
    )
    
    candidate_keywords = set(
        movies.iloc[candidate_index]['keyword_list']
    )
    
    if not movie_keywords:
        return 0
    
    return len(
        movie_keywords & candidate_keywords
    ) / len(movie_keywords)

In [74]:
keyword_similarity(
    avatar_index,
    serenity_index
)

0.0

In [75]:
def cast_similarity(movie_index, candidate_index):
    
    movie_cast = set(
        movies.iloc[movie_index]['cast_list']
    )
    
    candidate_cast = set(
        movies.iloc[candidate_index]['cast_list']
    )
    
    if not movie_cast:
        return 0
    
    return len(
        movie_cast & candidate_cast
    ) / len(movie_cast)

In [76]:
cast_similarity(
    avatar_index,
    serenity_index
)

0.0

In [77]:
def director_similarity(movie_index, candidate_index):
    
    movie_director = movies.iloc[movie_index]['director']
    candidate_director = movies.iloc[candidate_index]['director']
    
    if not movie_director or not candidate_director:
        return 0
    
    return float(
        movie_director == candidate_director
    )

In [78]:
director_similarity(
    avatar_index,
    serenity_index
)

0.0

In [82]:
def metadata_similarity(
    movie_index,
    candidate_index,
    genre_weight=0.40,
    keyword_weight=0.20,
    cast_weight=0.20,
    director_weight=0.20
):
    
    genre_score = genre_similarity(
        movie_index,
        candidate_index
    )
    
    keyword_score = keyword_similarity(
        movie_index,
        candidate_index
    )
    
    cast_score = cast_similarity(
        movie_index,
        candidate_index
    )
    
    director_score = director_similarity(
        movie_index,
        candidate_index
    )
    
    return (
        genre_weight * genre_score
        + keyword_weight * keyword_score
        + cast_weight * cast_score
        + director_weight * director_score
    )

In [80]:
metadata_similarity(
    avatar_index,
    serenity_index
)

0.1875

In [81]:
avatar_index = movies[
    movies['title'].str.lower() == 'avatar'
].index[0]

distances = hybrid_similarity[avatar_index]

top_movies = sorted(
    list(enumerate(distances)),
    reverse=True,
    key=lambda x: x[1]
)[1:6]

for i, score in top_movies:
    
    title = movies.iloc[i]['title']
    metadata_score = metadata_similarity(
        avatar_index,
        i
    )
    
    print(
        f"{title} | "
        f"Hybrid: {score:.4f} | "
        f"Metadata: {metadata_score:.4f}"
    )

Serenity | Hybrid: 0.6814 | Metadata: 0.1875
Jupiter Ascending | Hybrid: 0.6785 | Metadata: 0.2738
Barbarella | Hybrid: 0.6319 | Metadata: 0.0744
Close Encounters of the Third Kind | Hybrid: 0.6268 | Metadata: 0.0744
Battle: Los Angeles | Hybrid: 0.6178 | Metadata: 0.1488

In [83]:
metadata_similarity(
    avatar_index,
    serenity_index
)

0.30000000000000004

In [84]:
def v5_score(movie_index, candidate_index, metadata_weight=0.10):
    
    hybrid_score = hybrid_similarity[movie_index][candidate_index]
    
    metadata_score = metadata_similarity(
        movie_index,
        candidate_index
    )
    
    final_score = (
        (1 - metadata_weight) * hybrid_score
        + metadata_weight * metadata_score
    )
    
    return final_score

In [85]:
v5_score(
    avatar_index,
    serenity_index
)

np.float64(0.6432243987811596)

In [86]:
for i, hybrid_score in top_movies:
    
    title = movies.iloc[i]['title']
    
    metadata_score = metadata_similarity(
        avatar_index,
        i
    )
    
    final_score = v5_score(
        avatar_index,
        i
    )
    
    print(
        f"{title} | "
        f"Hybrid: {hybrid_score:.4f} | "
        f"Metadata: {metadata_score:.4f} | "
        f"V5: {final_score:.4f}"
    )

Serenity | Hybrid: 0.6814 | Metadata: 0.3000 | V5: 0.6432
Jupiter Ascending | Hybrid: 0.6785 | Metadata: 0.4190 | V5: 0.6526
Barbarella | Hybrid: 0.6319 | Metadata: 0.1095 | V5: 0.5797
Close Encounters of the Third Kind | Hybrid: 0.6268 | Metadata: 0.1095 | V5: 0.5751
Battle: Los Angeles | Hybrid: 0.6178 | Metadata: 0.2190 | V5: 0.5779

In [87]:
def evaluate_v5_on_indices(metadata_weight, indices):
    
    scores = []
    
    for index in indices:
        
        movie_genres = set(
            movies.iloc[index]['genre_list']
        )
        
        if len(movie_genres) == 0:
            continue
        
        distances = hybrid_similarity[index]
        
        movie_list = sorted(
            list(enumerate(distances)),
            reverse=True,
            key=lambda x: x[1]
        )[1:21]
        
        reranked = []
        
        for candidate_index, hybrid_score in movie_list:
            
            metadata_score = metadata_similarity(
                index,
                candidate_index
            )
            
            final_score = (
                (1 - metadata_weight) * hybrid_score
                + metadata_weight * metadata_score
            )
            
            reranked.append(
                (candidate_index, final_score)
            )
        
        reranked.sort(
            key=lambda x: x[1],
            reverse=True
        )
        
        top_5 = reranked[:5]
        
        total_score = 0
        
        for candidate_index, _ in top_5:
            
            recommended_genres = set(
                movies.iloc[candidate_index]['genre_list']
            )
            
            genre_score = (
                len(movie_genres & recommended_genres)
                / len(movie_genres)
            )
            
            total_score += genre_score
        
        scores.append(total_score / 5)
    
    return np.mean(scores), len(scores)

In [88]:
metadata_weights = [
    0.0,
    0.05,
    0.10,
    0.15,
    0.20,
    0.30,
    0.40,
    0.50
]

v5_results = []

for weight in metadata_weights:
    
    score, count = evaluate_v5_on_indices(
        weight,
        test_indices
    )
    
    v5_results.append({
        "metadata_weight": weight,
        "hybrid_weight": 1 - weight,
        "score": score,
        "movies_evaluated": count
    })

v5_results

[{'metadata_weight': 0.0,
  'hybrid_weight': 1.0,
  'score': np.float64(0.5783501683501684),
  'movies_evaluated': 99},
 {'metadata_weight': 0.05,
  'hybrid_weight': 0.95,
  'score': np.float64(0.6559932659932659),
  'movies_evaluated': 99},
 {'metadata_weight': 0.1,
  'hybrid_weight': 0.9,
  'score': np.float64(0.7139393939393942),
  'movies_evaluated': 99},
 {'metadata_weight': 0.15,
  'hybrid_weight': 0.85,
  'score': np.float64(0.7573737373737374),
  'movies_evaluated': 99},
 {'metadata_weight': 0.2,
  'hybrid_weight': 0.8,
  'score': np.float64(0.7838720538720539),
  'movies_evaluated': 99},
 {'metadata_weight': 0.3,
  'hybrid_weight': 0.7,
  'score': np.float64(0.8094276094276095),
  'movies_evaluated': 99},
 {'metadata_weight': 0.4,
  'hybrid_weight': 0.6,
  'score': np.float64(0.8162289562289563),
  'movies_evaluated': 99},
 {'metadata_weight': 0.5,
  'hybrid_weight': 0.5,
  'score': np.float64(0.8183164983164982),
  'movies_evaluated': 99}]

In [89]:
def evaluate_recommendations(indices, metadata_weight):
    
    semantic_scores = []
    genre_scores = []
    
    for index in indices:
        
        movie_genres = set(
            movies.iloc[index]['genre_list']
        )
        
        if len(movie_genres) == 0:
            continue
        
        # Get top 20 using the original hybrid model
        distances = hybrid_similarity[index]
        
        candidates = sorted(
            list(enumerate(distances)),
            reverse=True,
            key=lambda x: x[1]
        )[1:21]
        
        # Re-rank using V5
        reranked = []
        
        for candidate_index, hybrid_score in candidates:
            
            metadata_score = metadata_similarity(
                index,
                candidate_index
            )
            
            final_score = (
                (1 - metadata_weight) * hybrid_score
                + metadata_weight * metadata_score
            )
            
            reranked.append(
                (candidate_index, final_score)
            )
        
        reranked.sort(
            key=lambda x: x[1],
            reverse=True
        )
        
        top_5 = reranked[:5]
        
        # Evaluate the final recommendations
        semantic_total = 0
        genre_total = 0
        
        for candidate_index, _ in top_5:
            
            # Semantic relevance
            semantic_total += semantic_similarity[
                index
            ][candidate_index]
            
            # Genre relevance
            candidate_genres = set(
                movies.iloc[candidate_index]['genre_list']
            )
            
            genre_overlap = (
                len(movie_genres & candidate_genres)
                / len(movie_genres)
            )
            
            genre_total += genre_overlap
        
        semantic_scores.append(
            semantic_total / 5
        )
        
        genre_scores.append(
            genre_total / 5
        )
    
    return {
        "semantic_score": np.mean(semantic_scores),
        "genre_score": np.mean(genre_scores),
        "movies_evaluated": len(semantic_scores)
    }

In [91]:
semantic_similarity = np.load(
    "../data/artifacts/semantic_similarity.npy"
)

In [92]:
semantic_similarity.shape

(4803, 4803)

In [93]:
evaluate_recommendations(
    test_indices,
    0.5
)

{'semantic_score': np.float32(0.47958454),
 'genre_score': np.float64(0.8183164983164982),
 'movies_evaluated': 99}

In [94]:
evaluate_recommendations(
    test_indices,
    0.0
)

{'semantic_score': np.float32(0.49949765),
 'genre_score': np.float64(0.5783501683501684),
 'movies_evaluated': 99}

In [95]:
weights_to_test = [
    0.0,
    0.1,
    0.2,
    0.3,
    0.4,
    0.5
]

comparison_results = []

for weight in weights_to_test:
    
    result = evaluate_recommendations(
        test_indices,
        weight
    )
    
    comparison_results.append({
        "metadata_weight": weight,
        "hybrid_weight": 1 - weight,
        "semantic_score": result["semantic_score"],
        "genre_score": result["genre_score"],
        "movies_evaluated": result["movies_evaluated"]
    })

comparison_results

[{'metadata_weight': 0.0,
  'hybrid_weight': 1.0,
  'semantic_score': np.float32(0.49949765),
  'genre_score': np.float64(0.5783501683501684),
  'movies_evaluated': 99},
 {'metadata_weight': 0.1,
  'hybrid_weight': 0.9,
  'semantic_score': np.float32(0.4953536),
  'genre_score': np.float64(0.7139393939393942),
  'movies_evaluated': 99},
 {'metadata_weight': 0.2,
  'hybrid_weight': 0.8,
  'semantic_score': np.float32(0.48839858),
  'genre_score': np.float64(0.7838720538720539),
  'movies_evaluated': 99},
 {'metadata_weight': 0.3,
  'hybrid_weight': 0.7,
  'semantic_score': np.float32(0.48337346),
  'genre_score': np.float64(0.8094276094276095),
  'movies_evaluated': 99},
 {'metadata_weight': 0.4,
  'hybrid_weight': 0.6,
  'semantic_score': np.float32(0.4815327),
  'genre_score': np.float64(0.8162289562289563),
  'movies_evaluated': 99},
 {'metadata_weight': 0.5,
  'hybrid_weight': 0.5,
  'semantic_score': np.float32(0.47958454),
  'genre_score': np.float64(0.8183164983164982),
  'movies_evaluated': 99}]

In [96]:
v5_final = evaluate_recommendations(
    test_indices_final,
    0.1
)

hybrid_final = evaluate_recommendations(
    test_indices_final,
    0.0
)

print("ORIGINAL HYBRID")
print(hybrid_final)

print("\nV5 — 90% HYBRID + 10% METADATA")
print(v5_final)

ORIGINAL HYBRID
{'semantic_score': np.float32(0.4861824), 'genre_score': np.float64(0.5621548821548822), 'movies_evaluated': 99}

V5 — 90% HYBRID + 10% METADATA
{'semantic_score': np.float32(0.48213246), 'genre_score': np.float64(0.7122558922558925), 'movies_evaluated': 99}

In [2]:
%whos

Interactive namespace is empty.

In [4]:
import os

print(os.getcwd())

c:\Users\HP\pythoncode\personalized_entertainment_AI\notebooks

In [5]:
print(os.listdir())

['01_movies_data_exploration.ipynb']

In [6]:
import os
import sys

sys.path.append(os.path.abspath(".."))

In [7]:
from src.load_model import movies, hybrid_similarity

Model artifacts loaded successfully.
Movies: (4803, 29)
TF-IDF: (4803, 5000)
Hybrid: (4803, 4803)

In [8]:
movies.columns.tolist()

['budget',
 'genres',
 'homepage',
 'id',
 'keywords',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'production_companies',
 'production_countries',
 'release_date',
 'revenue',
 'runtime',
 'spoken_languages',
 'status',
 'tagline',
 'title',
 'vote_average',
 'vote_count',
 'movie_id',
 'title_y',
 'cast',
 'crew',
 'genre_list',
 'keyword_list',
 'cast_list',
 'director',
 'tags']

In [9]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,vote_count,movie_id,title_y,cast,crew,genre_list,keyword_list,cast_list,director,tags
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[action, adventure, fantasy, science fiction]","[culture clash, future, space war, space colon...","[sam worthington, zoe saldana, sigourney weave...",james cameron,"in the 22nd century, a paraplegic marine is di..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,4500,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[adventure, fantasy, action]","[ocean, drug abuse, exotic island, east india ...","[johnny depp, orlando bloom, keira knightley, ...",gore verbinski,"captain barbossa, long believed to be dead, ha..."

In [11]:
print(movies.columns.tolist())

['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language', 'original_title', 'overview', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'vote_average', 'vote_count', 'movie_id', 'title_y', 'cast', 'crew', 'genre_list', 'keyword_list', 'cast_list', 'director', 'tags']

In [12]:
print(movies[movies["title"] == "Jupiter Ascending"].head(1))

       budget                                             genres  \
61  176000003  [{"id": 878, "name": "Science Fiction"}, {"id"...

                           homepage     id  \
61  http://www.jupiterascending.com  76757

                                             keywords original_language  \
61  [{"id": 306, "name": "jupiter"}, {"id": 9882, ...                en

       original_title                                           overview  \
61  Jupiter Ascending  In a universe where human genetic material is ...

    popularity                               production_companies  ...  \
61    85.36908  [{"name": "Village Roadshow Pictures", "id": 7...  ...

   vote_count movie_id            title_y  \
61       2768    76757  Jupiter Ascending

                                                 cast  \
61  [{"cast_id": 6, "character": "Jupiter Jones", ...

                                                 crew  \
61  [{"credit_id": "5535bb999251414716001979", "de...

                                       genre_list  \
61  [science fiction, fantasy, action, adventure]

                                         keyword_list  \
61  [jupiter, space, woman director, 3d, interspec...

                                            cast_list         director  \
61  [mila kunis, channing tatum, sean bean, eddie ...  lilly wachowski

                                                 tags
61  in a universe where human genetic material is ...

[1 rows x 29 columns]

In [13]:
movie = movies[movies["title_y"] == "Jupiter Ascending"].iloc[0]

print("TITLE:", movie["title_y"])
print("OVERVIEW:", movie["overview"])
print("RELEASE DATE:", movie["release_date"])
print("RATING:", movie["vote_average"])
print("RUNTIME:", movie["runtime"])
print("GENRES:", movie["genre_list"])
print("CAST:", movie["cast_list"])
print("DIRECTOR:", movie["director"])

TITLE: Jupiter Ascending
OVERVIEW: In a universe where human genetic material is the most precious commodity, an impoverished young Earth woman becomes the key to strategic maneuvers and internal strife within a powerful dynasty…
RELEASE DATE: 2015-02-04
RATING: 5.2
RUNTIME: 124.0
GENRES: ['science fiction', 'fantasy', 'action', 'adventure']
CAST: ['mila kunis', 'channing tatum', 'sean bean', 'eddie redmayne', 'douglas booth']
DIRECTOR: lilly wachowski

In [14]:
import importlib
import src.recommender

importlib.reload(src.recommender)

In [15]:
from src.recommender import recommend_detailed

In [16]:
results = recommend_detailed("Avatar", n=1)

results

[{'index': 61,
  'title': 'Jupiter Ascending',
  'score': 0.6525766738740625,
  'hybrid_score': 0.6785243466325562,
  'metadata_score': 0.41904761904761906,
  'release_year': '2015',
  'rating': 5.2,
  'runtime': 124,
  'genres': ['science fiction', 'fantasy', 'action', 'adventure'],
  'overview': 'In a universe where human genetic material is the most precious commodity, an impoverished young Earth woman becomes the key to strategic maneuvers and internal strife within a powerful dynasty…',
  'cast': ['mila kunis',
   'channing tatum',
   'sean bean',
   'eddie redmayne',
   'douglas booth'],
  'director': 'lilly wachowski',
  'reasons': ['Shares 4 genre(s): action, adventure, fantasy, science fiction',
   'Shares 2 keyword(s)']}]

In [17]:
movies.columns.tolist()

['budget',
 'genres',
 'homepage',
 'id',
 'keywords',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'production_companies',
 'production_countries',
 'release_date',
 'revenue',
 'runtime',
 'spoken_languages',
 'status',
 'tagline',
 'title',
 'vote_average',
 'vote_count',
 'movie_id',
 'title_y',
 'cast',
 'crew',
 'genre_list',
 'keyword_list',
 'cast_list',
 'director',
 'tags']

In [1]:
import os

print("Notebook working directory:")
print(os.getcwd())

Notebook working directory:
c:\Users\HP\pythoncode\personalized_entertainment_AI\notebooks

In [2]:
print("Files in current directory:")
print(os.listdir())

Files in current directory:
['01_movies_data_exploration.ipynb']

In [5]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

print("Model loaded successfully")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Model loaded successfully

In [6]:
import pandas as pd

movies = pd.read_pickle(
    "../data/artifacts/movies_processed.pkl"
)

print("Movies loaded:", movies.shape)

Movies loaded: (4803, 29)

In [7]:
movie_embeddings = model.encode(
    movies["tags"].tolist(),
    show_progress_bar=True
)

print("Embedding shape:", movie_embeddings.shape)

Batches:   0%|          | 0/151 [00:00<?, ?it/s]

Embedding shape: (4803, 384)

In [8]:
import numpy as np
import os

artifact_dir = "../data/artifacts"

file_path = os.path.join(
    artifact_dir,
    "movie_embeddings.npy"
)

np.save(file_path, movie_embeddings)

print("Saved to:", os.path.abspath(file_path))
print("File exists:", os.path.exists(file_path))

Saved to: c:\Users\HP\pythoncode\personalized_entertainment_AI\data\artifacts\movie_embeddings.npy
File exists: True

In [9]:
print(movies.columns.tolist())

['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language', 'original_title', 'overview', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'vote_average', 'vote_count', 'movie_id', 'title_y', 'cast', 'crew', 'genre_list', 'keyword_list', 'cast_list', 'director', 'tags']